spring.application.name="GeoEventos API"

# Configuración del servidor
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=mi_usuario
spring.datasource.password=mi_password
spring.datasource.driver-class-name=org.postgresql.Driver

# IMGBB API
imgbb.api.key=6650ce52f2d80d5aa507b51ee94c8bd5
imgbb.api.url=https://api.imgbb.com/1/upload


spring.main.web-application-type=servlet
