spring.application.name="GeoEventos API"

# Configuracion del servidor

# Configuracion de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=${SERVER_PORT:8080}
spring.datasource.driver-class-name=org.postgresql.Driver

# IMGBB API
imgbb.api.key=${IMGBB_API_KEY}
imgbb.api.url=${IMGBB_URL}

spring.main.web-application-type=servlet
